export const Locators = {
    HomeTab: '~Home',
    WebviewTab: '~Webview',
    LoginTab: '~Login',
    FormsTab: '~Forms',
    SwipeTab: '~Swipe',
    DragTab: '~Drag',
    MenuTab: '~Menu',

    HomeScreen: '~Home-screen',
    WebviewScreen: '//android.webkit.WebView',
    LoginScreen: '~Login-screen',
    FormsScreen: '~Forms-screen',

    SideMenuPanel: '~tab-side-menu-panel',
    MenuItems: [
        'side-menu-item-home',
        'side-menu-item-webview',
        'side-menu-item-login',
        'side-menu-item-forms',
        'side-menu-item-swipe',
        'side-menu-item-drag',
        'side-menu-item-permissions',
        'side-menu-item-data-management',
    ],
    StarIcons: [
        'side-menu-star-webview',
        'side-menu-star-login',
        'side-menu-star-forms',
        'side-menu-star-swipe',
        'side-menu-star-drag',
        'side-menu-star-permissions',
        'side-menu-star-data-management',
    ],

    MenuHomeItem: '~side-menu-item-home',
    MenuWebviewItem: '~side-menu-item-webview',

    SignUpTab: '//android.widget.TextView[@text="Sign up"]',
    EmailInput: '~input-email',
    PasswordInput: '~input-password',
    RepeatPasswordInput: '~input-repeat-password',
    SignUpButton: '~button-SIGN UP',
    LoginButton: '~button-LOGIN',
    OkButton: '//*[@text="OK"]',

    FormInput: '~text-input',
    FormInputResult: '~input-text-result',
    FormSwitch: '~switch',
    FormSwitchText: '~switch-text',
    FormDropdown: '~Dropdown',
    FormActiveButton: '~button-Active',
    FormInactiveButton: '~button-Inactive',
};
